
target("assimp")
    set_kind("static")
    add_defines("ASSIMP_BUILD_NO_IFC_IMPORTER")
    add_defines("ASSIMP_BUILD_NO_C4D_IMPORTER")
    add_includedirs("./include", {public=true})
    add_includedirs("./", {public=false})
    add_includedirs("./code", {public=false})
    add_includedirs("./code/Step", {public=false})
    add_includedirs("./contrib/irrXML", {public=false})
    add_includedirs("./contrib/zlib", {public=false})
    add_includedirs("./contrib/rapidjson/include", {public=false})
    add_includedirs("./contrib/openddlparser/include", {public=false})
    add_includedirs("./contrib/unzip", {public=false})
    add_files("./code/**.cpp")
    add_files("./code/**.c")
    add_files("./contrib/**.c")
    add_files("./contrib/**.cc")
    add_files("./contrib/**.cpp")
    del_files("./contrib/zlib/contrib/testzlib/testzlib.c")
    del_files("./contrib/zlib/contrib/minizip/iowin32.c")
    del_files("./contrib/zip/test/*.c")
    del_files("./contrib/zlib/contrib/iostream/*.cpp")
    del_files("./contrib/zlib/contrib/iostream2/*.cpp")
    del_files("./contrib/gtest/**.*")

